# Ref: https://github.com/marketplace/actions/github-labeler
# Ref: https://github.com/cjolowicz/cookiecutter-hypermodern-python/blob/main/%7B%7Bcookiecutter.project_name%7D%7D/.github/labels.yml

# Default GitHub labels
- name: duplicate
  description: This issue or pull request already exists
  color: cfd3d7
- name: "good first issue"
  description: Good for newcomers
  color: 7057ff
- name: "help wanted"
  description: Extra attention is needed
  color: "008672"
- name: invalid
  description: This doesn't seem right
  color: e4e669
- name: question
  description: Further information is requested
  color: d876e3
- name: wontfix
  description: This will not be worked on
  color: ffffff

# Status
- name: "status: abandoned"
  color: "000000"
- name: "status: accepted"
  color: "009800"
- name: "status: blocked"
  color: e11d21
- name: "status: pending"
  color: 7c3ea5 # TODO hellblau?

# Type
- name: "type: bug"
  description: Something isn't working
  color: e11d21
- name: "type: build"
  description: Changes that affect the build system or external dependencies
  color: cfd3d7 # TODO
- name: "type: ci"
  description: Continuous Integration
  color: "000000"
- name: "type: chore"
  description: Miscellaneous changes (e.g. .gitignore, static files)
  color: cfd3d7
- name: "type: docs"
  description: Improvements or additions to documentation
  color: "0075ca"
- name: "type: feature"
  description: New feature or request
  color: "009800"
- name: "type: performance"
  description: Changes that improve performance
  color: "009800" # TODO
- name: "type: refactor"
  description: Changes that neither fix a bug nor adds a feature
  color: "009800" # TODO
- name: "type: style"
  description: Changes that do not affect the meaning of the code (e.g. white-space, formatting)
  color: e11d21 # TODO
- name: "type: test"
  description: Adding missing tests or correcting existing tests
  color: 7c3ea5 # TODO blau?

# Priority
- name: "priority: low"
  color: "009800"
- name: "priority: medium"
  color: fbca04
- name: "priority: high"
  color: eb6420
- name: "priority: critical"
  color: e11d21

# Dependencies
- name: "deps: python"
  description: Pull requests that update Python code
  color: 2b67c6
- name: "deps: github-actions"
  description: Pull requests that update GitHub Actions code
  color: "000000"
- name: "deps: pre-commit"
  description: Pull requests that update pre-commit config code
  color: fbca04
