# Ref: GitHub Action https://github.com/marketplace/actions/github-labeler.

# Standard

# Status
- name: "status: approved"
  color: 7c3ea5
- name: "status: blocked"
  color: 7c3ea5
- name: "status: inactive"
  color: 7c3ea5
- name: "status: pending"
  color: 7c3ea5

# Type
- name: "type: bug"
  color: 7c3ea5
- name: "type: chore"
  color: 7c3ea5
- name: "type: discussion"
  color: 7c3ea5
- name: "type: docs"
  color: 7c3ea5
- name: "type: feature"
  color: 7c3ea5
- name: "type: question"
  color: 7c3ea5
- name: "type: security"
  color: 7c3ea5
- name: "type: testing"
  color: 7c3ea5

# Priority
- name: "priority: low"
  color: "009800"
- name: "priority: medium"
  color: fbca04
- name: "priority: high"
  color: eb6420
- name: "priority: critical"
  color: e11d21
