# Ref: GitHub Action https://github.com/marketplace/actions/github-labeler.

# Default GitHub labels
- name: duplicate
  description: This issue or pull request already exists 
  color: cfd3d7
- name: "good first issue"
  description: Good for newcomers
  color: 7057ff
- name: "help wanted"
  description: Extra attention is needed
  color: 008672
- name: invalid
  description: This doesn't seem right
  color: e4e669
- name: wontfix
  description: This will not be worked on 
  color: ffffff

# Status
- name: "status: approved"
  color: 7c3ea5
- name: "status: blocked"
  color: e11d21
- name: "status: inactive"
  color: 7c3ea5
- name: "status: pending"
  color: 7c3ea5
- name: "status: abandoned"
  color: "000000"

# Type
- name: "type: bug"
  description: Something isn't working
  color: e11d21
- name: "type: chore"
  color: 7c3ea5
- name: "type: discussion"
  color: 7c3ea5
- name: "type: docs"
  description: Improvements or additions to documentation
  color: 7c3ea5
- name: "type: feature"
  description: New feature or request
  color: 7c3ea5
- name: "type: question"
  color: 7c3ea5
- name: "type: security"
  color: e11d21
- name: "type: testing"
  color: 7c3ea5

# Priority
- name: "priority: low"
  color: "009800"
- name: "priority: medium"
  color: fbca04
- name: "priority: high"
  color: eb6420
- name: "priority: critical"
  color: e11d21

# Dependencies
- name: python
  description: Pull requests that update Python code
  color: 2b67c6
- name: pre-commit
  description: Pull requests that update pre-commit config code
  color: fbca04
- name: github-actions
  description: Pull requests that update GitHub Actions code
  color: "000000"
