# Ref: GitHub Action https://github.com/marketplace/actions/github-labeler.

# Default GitHub labels
- name: duplicate
  description: This issue or pull request already exists 
  color: cfd3d7
- name: "good first issue"
  description: Good for newcomers
  color: 7057ff
- name: "help wanted"
  description: Extra attention is needed
  color: "008672"
- name: invalid # TODO: status?
  description: This doesn't seem right
  color: e4e669
- name: wontfix # TODO: status?
  description: This will not be worked on 
  color: ffffff

# Status
- name: "status: abandoned"
  color: "000000"
- name: "status: accepted"
  color: "009800"
- name: "status: blocked"
  color: e11d21
- name: "status: pending"
  color: 7c3ea5 # TODO

# Type
- name: "type: bug"
  description: Something isn't working
  color: e11d21
- name: "type: chore"
  description: TODO
  color: cfd3d7
- name: "type: discussion"
  description: TODO
  color: 7c3ea5 # TODO
- name: "type: docs"
  description: Improvements or additions to documentation
  color: "0075ca"
- name: "type: feature"
  description: New feature or request
  color: "009800"
- name: "type: question"
  description: Further information is requested
  color: d876e3
- name: "type: security"
  description: TODO
  color: e11d21
- name: "type: testing"
  description: TODO
  color: 7c3ea5 # TODO

# Priority
- name: "priority: low"
  color: "009800"
- name: "priority: medium"
  color: fbca04
- name: "priority: high"
  color: eb6420
- name: "priority: critical"
  color: e11d21

# Dependencies
- name: "deps: python"
  description: Pull requests that update Python code
  color: 2b67c6
- name: "deps: github-actions"
  description: Pull requests that update GitHub Actions code
  color: "000000"
- name: "deps: pre-commit"
  description: Pull requests that update pre-commit config code
  color: fbca04
