# pre-commit
# Ref: https://pre-commit.com/#usage
# ------------------------------------------------------------------------------

# Ref: https://pre-commit.com/#regular-expressions
# CHANGELOG.md: semantic-release autocreates this file
exclude: |
  (?x)^(
    CHANGELOG.md
  )$

repos:
  # Ref: https://pre-commit.com/#meta-hooks
  - repo: meta
    hooks:
      - id: check-hooks-apply

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9 # frozen: v4.4.0
    hooks:
      - id: check-ast
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 8b471efae3d43e296d11e986d40fde050db4933e # frozen: 0.13.1
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/psf/black
    rev: 193ee766ca496871f93621d6b58d57a6564ff81b # frozen: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: b9787ef94f0d06972b93b36730548f0d928f26f9 # frozen: v0.0.285
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 672abe14d309fc28817d45b6be25ea976a92222a # frozen: v3.0.2
    hooks:
      - id: prettier
        # .git/COMMIT_EDITMSG: conventional-pre-commit needs to read this file
        exclude: .git/COMMIT_EDITMSG

  - repo: https://github.com/FHPythonUtils/LicenseCheck/
    rev: 0fb4c3849b7de5d6fd3cbb3dd26317e57a738814 # frozen: 2023.3
    hooks:
      - id: licensecheck

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: 7f91e1434e195a0121bc66bd50426f2140b5f862 # frozen: v2.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
