# pre-commit
# Ref: https://pre-commit.com/#usage
# ------------------------------------------------------------------------------

# Ref: https://pre-commit.com/#regular-expressions
# CHANGELOG.md: semantic-release autocreates this file
exclude: |
  (?x)^(
    CHANGELOG.md
  )$

repos:
  # Ref: https://pre-commit.com/#meta-hooks
  - repo: meta
    hooks:
      - id: check-hooks-apply

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: c4a0b883114b00d8d76b479c820ce7950211c99b  # frozen: v4.5.0
    hooks:
      - id: check-ast
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: b5b0cb0c9d8211a8782e71c54f1730f37a1624fa  # frozen: 1.1.0
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/psf/black
    rev: e87737140f32d3cd7c44ede75f02dcd58e55820e  # frozen:  23.9.1
    hooks:
      - id: black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 382100c524aa3fa39218d6262f0cbf02dffae4db  # frozen: v0.1.0
    hooks:
      - id: ruff

  - repo: https://github.com/FHPythonUtils/LicenseCheck/
    rev: 15cc02a0c636c5e0caac505d6bfcfd70e17871e9  # frozen: 2023.5.1
    hooks:
      - id: licensecheck

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: 09c004511d352e92003e76c8152dafd200c314e3  # frozen: v2.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
