# pre-commit
# Ref: https://pre-commit.com/#usage
# ------------------------------------------------------------------------------

# Ref: https://pre-commit.com/#regular-expressions
# CHANGELOG.md: semantic-release autocreates this file
exclude: |
  (?x)^(
    CHANGELOG.md
  )$

repos:
  # Ref: https://pre-commit.com/#meta-hooks
  - repo: meta
    hooks:
      - id: check-hooks-apply

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9 # frozen: v4.4.0
    hooks:
      - id: check-ast
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: a7b43f63524fa3d7d91db7c9ef67986c50a54829 # frozen: 0.13.0
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/psf/black
    rev: 193ee766ca496871f93621d6b58d57a6564ff81b # frozen: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: b9a5dc23ed421f99c0fe14b9ace2cbc7fbf710bd # frozen: v0.0.284
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 39f806769667765a1d55ea736d62bb8f72993e01 # frozen: v3.0.1
    hooks:
      - id: prettier
        # .git/COMMIT_EDITMSG: conventional-pre-commit needs to read this file
        exclude: .git/COMMIT_EDITMSG

  - repo: https://github.com/FHPythonUtils/LicenseCheck/
    rev: 0fb4c3849b7de5d6fd3cbb3dd26317e57a738814 # frozen: 2023.3
    hooks:
      - id: licensecheck

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: 7f91e1434e195a0121bc66bd50426f2140b5f862 # frozen: v2.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
