# pre-commit
# Ref: https://pre-commit.com/#usage
# ------------------------------------------------------------------------------

# Ref: https://pre-commit.com/#regular-expressions
# CHANGELOG.md: semantic-release autocreates this file
exclude: |
  (?x)^(
    CHANGELOG.md
  )$

repos:
  # Ref: https://pre-commit.com/#meta-hooks
  - repo: meta
    hooks:
      - id: check-hooks-apply

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: c4a0b883114b00d8d76b479c820ce7950211c99b  # frozen: v4.5.0
    hooks:
      - id: check-ast
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: c24c4b6b809359c7ff08cb78ea266d361407c0da  # frozen: 1.5.2
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 75d1925b523dd109cc200d1b29142ff36ec785ad  # frozen: v0.1.6
    hooks:
    - id: ruff-format
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/FHPythonUtils/LicenseCheck/
    rev: 15cc02a0c636c5e0caac505d6bfcfd70e17871e9  # frozen: 2023.5.1
    hooks:
      - id: licensecheck

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: 09de2d8736611042feeff83688b5b5b35d459c7c  # frozen: v3.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
