# mkdocs
# Ref: https://www.mkdocs.org/user-guide/configuration/
# ------------------------------------------------------------------------------

site_name: services-test4
site_description: services-test4
repo_name: afuetterer/services-test4
repo_url: https://github.com/afuetterer/services-test4
watch: [README.md, src/services_test4]

nav:
  - Home: index.md
  # - Usage: cli.md
  # - Reference: reference/
  - Changelog: changelog.md
  - License: license.md

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - content.code.annotate

plugins:
  - search
  # - mkdocstrings:
  #     handlers:
  #       python:
  #         options:
  #           docstring_style: google
  - include-markdown
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index

markdown_extensions:
  - admonition
  - mkdocs-click

extra:
  version:
    provider: mike
