# mkdocs
# Ref: https://www.mkdocs.org/user-guide/configuration/
# ------------------------------------------------------------------------------

site_name: services-test4
site_description: services-test4
site_url: https://afuetterer.github.io/services-test4
repo_name: afuetterer/services-test4
repo_url: https://github.com/afuetterer/services-test4
docs_dir: src
edit_uri: edit/main/docs/
strict: true
watch:
- ../src

nav:
  - Home: index.md
  - Changelog: changelog.md
  - License: license.md

theme:
  name: material
  custom_dir: src/overrides
  features:
    - content.code.annotate

plugins:
  - search
  # - mkdocstrings:
  #     handlers:
  #       python:
  #         options:
  #           docstring_style: google
  - include-markdown

markdown_extensions:
  - admonition
  - mkdocs-click

extra:
  version:
    provider: mike
