name: cd

on:
  push:
    branches: [main]

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

permissions:
  contents: read

jobs:
  build:
    # do not run in forks
    if: github.repository == 'afuetterer/services-test4'
    name: Build Python package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Set up Python 3.11
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
        with:
          python-version: "3.11"
          cache: pip

      - name: Ensure latest pip
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install hatch
        run: pip install --upgrade hatch

      - name: Build package
        run: hatch build
