name: CD

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    branches: ["main"]
    types:
      - completed

concurrency:
  group: cd-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

permissions:
  contents: read

jobs:
  release:
    # do not run in forks
    if: >-
      github.repository == 'afuetterer/services-test4'
      && ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build Python package
    runs-on: ubuntu-22.04
    concurrency: release

    # permissions:
    #   id-token: write
    #   contents: write

    # https://python-semantic-release.readthedocs.io/en/latest/automatic-releases/github-actions.html

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 0
          token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

      - name: Set up Python 3.11
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
        with:
          python-version: "3.11"
          cache: pip

      - name: Ensure latest pip
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install hatch
        run: pip install --upgrade hatch

      - name: Build package
        run: hatch build

      - name: Create release
        run: hatch run release:version
        env:
          GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

      # TODO: token etc.
      # hatch build?

      # - name: Python Semantic Release
      #   uses: python-semantic-release/python-semantic-release@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
