name: Docs

on:
  release:
    types: [created]

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: docs-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  docs:
    # do not run in forks
    if: github.repository == 'afuetterer/services-test4'
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Set up Python 3.11
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
        with:
          python-version: "3.11"

      - uses: actions/cache@v3
        with:
          key: docs-${{ hashFiles('pyproject.toml') }}
          path: ~/.cache/pip

      - name: Ensure latest pip
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install hatch
        run: pip install --upgrade hatch

      - name: Build documentation
        run: hatch run docs:build

      - name: Deploy documentation
        run: hatch run docs:deploy
