name: Docs

on:
  release:
    types: [created]
  workflow_call:

concurrency:
  group: docs-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  docs:
    # do not run in forks
    if: github.repository == 'afuetterer/services-test4'
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up Python 3.11
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: "3.11"
      - uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319 # v4.0.1
        with:
          key: docs-${{ hashFiles('pyproject.toml') }}
          path: ~/.cache/pip
      - name: Install pre-requisites (e.g. hatch)
        run: python -m pip install --require-hashes --requirement=.github/requirements/ci.txt
      - name: Build documentation
        run: hatch run docs:build
      - name: Deploy documentation
        run: hatch run docs:deploy
        if: github.event_name == 'release'
