name: Label

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
      - .github/workflows/label.yml

permissions:
  contents: read

jobs:
  labeler:
    permissions:
      issues: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v4.1.0
