name: Label

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
      - .github/workflows/label.yml

permissions:
  contents: read

jobs:
  labeler:
    permissions:
      issues: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@f4f6b96e7e747b5416cd470f3cfecf26abaa811e # v4.2.0
