name: Lint

on:
  workflow_call:

env:
  PYTHONUNBUFFERED: 1
  FORCE_COLOR: 1 # colored output by pytest etc.
  CLICOLOR_FORCE: 1 # colored output by ruff

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up Python 3.12
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: "3.12"
          cache: pip
      - name: Install pre-requisites (e.g. hatch)
        run: python -m pip install --require-hashes --requirement=.github/requirements/ci.txt
      - name: Set up pre-commit cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: ~/.cache/pre-commit
          key: lint-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Run linters
        run: hatch run lint:all
