name: CI

on:
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: 1
  FORCE_COLOR: 1 # colored output by pytest etc.

permissions:
  contents: read

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml

  release:
    # do not run in forks
    if: github.repository == 'afuetterer/services-test4'
    name: Semantic release
    runs-on: ubuntu-22.04
    needs:
      - lint
      - test
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
          token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
      - name: Update version and date in CITATION.cff
        run: |
          pipx install hatch
          hatch run release:update-citation
          git add CITATION.cff
      - name: Create semantic release
        id: semantic-release
        uses: python-semantic-release/python-semantic-release@02fa4d21a2f06f31a8088508c6eacb57ee08f1b8 # v9.6.0
        with:
          github_token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
          git_committer_name: github-actions[bot]
          git_committer_email: 41898282+github-actions[bot]@users.noreply.github.com

      - name: Publish package distributions to GitHub Releases
        if: ${{ steps.semantic-release.outputs.released }} == 'true'
        uses: python-semantic-release/upload-to-gh-release@main
        with:
          github_token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
          root_options: -vv
