name: CI

on:
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: 1
  FORCE_COLOR: 1 # colored output by pytest etc.

permissions:
  contents: read

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml

  release:
    # do not run in forks
    if: github.repository == 'afuetterer/services-test4'
    name: Semantic release
    runs-on: ubuntu-22.04
    needs:
      - lint
      - test
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          disable-sudo: true
          # disable-telemetry: true
          egress-policy: audit
          # allowed-endpoints: >
          #   github.com:443
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
          token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
      - name: Create semantic release
        id: semantic-release
        uses: python-semantic-release/python-semantic-release@3a571d2622de93fab7844465db9c442846c8b78d # v8.5.0
        with:
          github_token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
          git_committer_name: github-actions[bot]
          git_committer_email: 41898282+github-actions[bot]@users.noreply.github.com

      - name: Publish package distributions to GitHub Releases
        id: github-release
        if: steps.semantic-release.outputs.released == 'true'
        uses: python-semantic-release/upload-to-gh-release@main
        with:
          github_token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
          tag: ${{ steps.release.outputs.tag }}
