name: CI

on:
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: 1
  FORCE_COLOR: 1 # colored output by pytest etc.

permissions:
  contents: read

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml

  release:
    # do not run in forks
    if: github.repository == 'afuetterer/services-test4'
    name: Semantic release
    runs-on: ubuntu-22.04
    needs:
      - lint
      - test
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          disable-sudo: true
          # disable-telemetry: true
          egress-policy: audit
          # allowed-endpoints: >
          #   github.com:443
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 0
          token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
      - name: Create semantic release
        id: semantic-release
        uses: python-semantic-release/python-semantic-release@3c7db14e7c1898bd4c1e748b3fa20a2d5eef3abe # v8.0.7
        with:
          github_token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
          git_committer_name: github-actions[bot]
          git_committer_email: 41898282+github-actions[bot]@users.noreply.github.com

      - name: Publish package distributions to GitHub Releases
        id: github-release
        if: steps.semantic-release.outputs.released == 'true'
        uses: python-semantic-release/upload-to-gh-release@main
        with:
          github_token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
          tag: ${{ steps.release.outputs.tag }}
