name: Test and release

on:
  push:
    branches: [main]

concurrency:
  group: main-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: 1
  FORCE_COLOR: 1 # colored output by pytest etc.
  CLICOLOR_FORCE: 1 # colored output by ruff

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Set up Python 3.11
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
        with:
          python-version: "3.11"
          cache: pip
      - name: Ensure latest pip
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install hatch
        run: pip install --upgrade hatch
      - name: Set up pre-commit cache
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: ~/.cache/pre-commit
          key: lint-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Run linters
        run: hatch run lint:all

  test:
    uses: ./.github/workflows/test.yml

  release:
    # do not run in forks
    if: github.repository == 'afuetterer/services-test4'
    name: Semantic release
    runs-on: ubuntu-22.04
    needs:
      - lint
      - test
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          disable-sudo: true
          egress-policy: audit
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 0
          token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
      - name: Create semantic release
        uses: python-semantic-release/python-semantic-release@9d3c0239fd3be0e4644c609aa2bed7afdca98e90 # v8.0.6
        with:
          github_token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
          git_committer_name: github-actions[bot]
          git_committer_email: 41898282+github-actions[bot]@users.noreply.github.com

  # TODO: python-semantic-release/upload-to-gh-release
