# This CI job is adapted from:
# Cookiecutter Django (2013-10-17), BSD-3-Clause license
# Ref: https://github.com/cookiecutter/cookiecutter-django/blob/2023.10.17/.github/workflows/pre-commit-autoupdate.yml

name: Update pre-commit hooks

on:
  schedule:
    # run once a month at midnight of the first day of the month
    - cron: 0 0 1 * *
  # run manually from actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  auto-update:
    # Disables this workflow from running in a repository that is not part of the indicated organization/user
    if: github.repository_owner == 'afuetterer'
    permissions:
      contents: write # for peter-evans/create-pull-request to create branch
      pull-requests: write # for peter-evans/create-pull-request to create a PR
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: "3.12"
          cache: pip
      - run: python -m pip install pre-commit
      - run: pre-commit autoupdate --freeze > autoupdate.log
      - name: Prepare message for pr body
        run: |
          grep "updating" autoupdate.log > updates.log
          sed -i -e 's/\[/- </g' updates.log
          sed -i -e 's/\]/>/g' updates.log
          echo -e "## Proposed changes\n\nBumps the pre-commit config with the following updates:\n" > pr-body.md
          cat updates.log >> pr-body.md
          echo -e "\n---\nThis PR is auto-generated once a month." >> pr-body.md
      # Ref: https://github.com/peter-evans/create-pull-request
      - name: Create pull request
        uses: peter-evans/create-pull-request@a4f52f8033a6168103c2538976c07b467e8163bc # v6.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: pre-commit-autoupdate
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          title: "build(deps-dev): update pre-commit hooks"
          commit-message: "build(deps-dev): update pre-commit hooks"
          add-paths: .pre-commit-config.yaml
          body-path: pr-body.md
          labels: |
            type: build
            deps: pre-commit
          delete-branch: true
      - name: Write to job summary
        run: |
          cat updates.log >> $GITHUB_STEP_SUMMARY
