name: Publish

on:
  release:
    types: [created]
  workflow_dispatch:

# Set permissions at the job level.
permissions: {}

jobs:
  build:
    name: Build the package
    runs-on: ubuntu-24.04
    permissions:
      attestations: write
      id-token: write
    steps:
    - run: sudo apt-get install tree # workaround for "tree: command not found" in baipp
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
    - uses: hynek/build-and-inspect-python-package@4aea7de65ba374f49b5f549cd471b61de2ef19d3 # v2.5.0
      with:
        attest-build-provenance-github: 'true'

  publish:
    # do not run in forks
    if: github.repository == 'afuetterer/services-test4'
    runs-on: ubuntu-24.04
    needs: build
    environment: publish
    permissions:
      id-token: write
    steps:
      - name: Download package built by build job
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          name: Packages
          path: dist

      - run: ls -l dist

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@81e9d935c883d0b210363ab89cf05f3894778450 # v1.8.14
        with:
          repository-url: https://test.pypi.org/legacy/
