name: Publish

on:
  release:
    types: [created]
  workflow_dispatch:

concurrency:
  group: publish-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  publish:
    # do not run in forks
    if: github.repository == 'afuetterer/services-test4'
    runs-on: ubuntu-22.04
    environment: publish
    permissions:
      id-token: write
    steps:

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: "3.12"
          cache: pip

      - name: Ensure latest pip
        run: python -m pip install --upgrade pip
      - run: python -m pip install build
      - run: python -m build

      - name: Publish package to Test PyPI
        uses: pypa/gh-action-pypi-publish@2f6f737ca5f74c637829c0f5c3acd0e29ea5e8bf # v1.8.11
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
