name: Publish

on:
  release:
    types: [created]
  workflow_dispatch:

concurrency:
  group: publish-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  publish:
    # do not run in forks
    if: github.repository == 'afuetterer/services-test4'
    runs-on: ubuntu-22.04
    environment: publish
    permissions:
      id-token: write
    steps:
      - name: Publish package to Test PyPI
        uses: pypa/gh-action-pypi-publish@2f6f737ca5f74c637829c0f5c3acd0e29ea5e8bf # v1.8.11
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
