name: Publish

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    # do not run in forks
    if: github.repository == 'afuetterer/services-test4'
    runs-on: ubuntu-22.04
    environment: publish
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: "3.12"
          cache: pip
      - run: python -m pip install build[uv]
      - run: python -m build
      - name: Publish package to Test PyPI
        uses: pypa/gh-action-pypi-publish@81e9d935c883d0b210363ab89cf05f3894778450 # v1.8.14
        with:
          repository-url: https://test.pypi.org/legacy/
