# Ref: https://github.com/actions/stale
name: Close stale issues and PRs

on:
  schedule:
    # run once a month at midnight of the first day of the month
  - cron: 0 0 1 * *
  # run manually from actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  stale:
    runs-on: ubuntu-22.04
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v9.0.0
        with:
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
          days-before-stale: 90
          days-before-close: 14
