# This CI job is adapted from:
# build-and-inspect-python-package (2024-03-25), MIT license
# Ref: https://github.com/hynek/build-and-inspect-python-package/blob/v2.2.1/.github/workflows/update-dependencies.yml

name: Upgrade requirements

on:
  schedule:
    # run once a month at midnight of the first day of the month
    - cron: 0 0 1 * *
  # run manually from actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  upgrade:
    permissions:
      contents: write # for peter-evans/create-pull-request to create branch
      pull-requests: write # for peter-evans/create-pull-request to create a PR
    name: Upgrade requirements
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Upgrade Python dependencies
        run: >
          uv pip compile
          --upgrade
          --generate-hashes
          --python-version=3.10
          --output-file=.github/requirements/ci.txt
          .github/requirements/ci.in

      # Ref: https://github.com/peter-evans/create-pull-request
      - name: Create pull request
        uses: peter-evans/create-pull-request@a4f52f8033a6168103c2538976c07b467e8163bc # v6.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: requirement-upgrades
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          title: "build(deps-dev): upgrade ci requirements"
          commit-message: "build(deps-dev): upgrade ci requirements"
          add-paths: .github/requirements/ci.txt
          labels: |
            type: build
            deps: python
          delete-branch: true
